name = "LocalRegistry"
uuid = "58f99493-34ed-41e3-b59d-7bb12b9b1c6c"
repo = "https://github.com/pmarg/Registry.git"
description = "Local Registry"

[packages]
64fa5d70-d699-11e8-15b1-b5d2f9a37380 = { name = "EconTools", path = "E/EconTools" }
